version: '1'

services:
	postgres:
		image: postgres:9.6
		container_name: postgres
		environment:
			POSTGRES_USER: loans
			POSTGRES_PASSWORD: J5brHrAXFLQSif0K
			POSTGRES_DB: loans

	loans:
		build: .
		image: chamaconekt/loans
		links:
		- postgres
		container_name: loans
		depends_on:
			- postgres
		environment:

	nginx:
		image: nginx:1.11.11-alpine
		links:
			- loans
		container_name: nginx
		command: nginx -g 'daemon off;' -c /etc/loans-nginx/nginx.conf
		depends_on:
			- loans
		ports:
			- 80:80
		volumes_from:
			- loans

volumes:
	loans-static-files:
		driver:local